### ISSUE TITLE
Missing run-time dependency: libignition-plugin-dev

### ISSUE THREAD

**Issue by scpeters** [gazebo-release/gz-rendering6-release#9]
As noted in https://github.com/ignitionrobotics/ign-sensors/pull/209#pullrequestreview-923419914, downstream packages that install `libignition-rendering6-dev` fail to find `ignition-plugin`, which is a [required dependency](https://github.com/ignitionrobotics/ign-rendering/blob/ignition-rendering6_6.2.1/CMakeLists.txt#L44) of ign-rendering6. I think we just need to add `libignition-plugin-dev` to the control file.

**Comment by j-rivero** [comment]
ready in #10
